/* eslint import/no-extraneous-dependencies: 1 */

import express from 'express';
import http from 'http';


// We build a list of promises that need to be resolved before we can start serving.
const startupPromises = [];


let webpackDevMiddleware;
let webpackHotMiddleware;

// This helper is required when we enable HMR.
// The reason for this is that we want the HMR middlewares to execute before the app.
const appWithHmr = app => {
    const wrapper = express();
    wrapper.use(webpackDevMiddleware);
    wrapper.use(webpackHotMiddleware);
    wrapper.use(app);
    return wrapper;
};


if (__DEV__) {
    const webpack = require('webpack');
    const config = require('../../webpack.client.babel').default();
    config.mode = 'development';
    const compiler = webpack(config);

    startupPromises.push(new Promise((resolve, reject) => {
        compiler.plugin('done', stats => {
            if (stats.hasErrors()) {
                reject(new Error('Compilation of client code failed.'));
            } else {
                resolve();
            }
        });
    }));

    // Client bundles
    const WebpackDevMiddleware = require('webpack-dev-middleware');
    webpackDevMiddleware = WebpackDevMiddleware(compiler, {
        publicPath: config.output.publicPath,
        mode: 'development',
        stats: config.stats,
    });

    // Client hot module reloading
    const WebpackHotMiddleware = require('webpack-hot-middleware');
    webpackHotMiddleware = WebpackHotMiddleware(compiler);
}


Promise.all(startupPromises)
    .then(() => {
        // The application needs to be imported *after* the client bundle is generated.
        // This is because we want to include 'assets.json' inside renders.jsx and that
        // file is generated by the client-side webpack configuration.
        const app = require('./app').default;
        let currentApp = __DEV__ ? appWithHmr(app) : app;

        // Start server
        const server = http.createServer(currentApp);
        const port = process.env.PORT || 3000;

        server.listen(port, () => {
            const addr = server.address();
            if (server.address && server.port) {
                console.log(`Server listening at http://${addr.address}:${addr.port}`);
            } else {
                console.log(`Server listening at http://localhost:${port}`);
            }
        });

        if (module.hot) {
            module.hot.accept('./app', () => {
                server.removeListener('request', currentApp);
                // Not sure why I need to explicitly require('./app') each time, but I do.
                // When I was doing "import app from './app" at the top of the file, 'app'
                // would automatically be re-imported. Not so with require().
                currentApp = appWithHmr(require('./app').default);
                server.on('request', currentApp);
            });
        }
    })
    .catch(error => {
        console.error(error);
        process.exit(1);
    });
